// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU4wvgT6TsJ-JFD9TrN-IrV0zriPjQgbk',
    appId: '1:274382156691:web:dcc1d5b072010b4d096e66',
    messagingSenderId: '274382156691',
    projectId: 'bakecakeadmin',
    authDomain: 'bakecakeadmin.firebaseapp.com',
    storageBucket: 'bakecakeadmin.appspot.com',
    measurementId: 'G-86DSN0J5JE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgCMXxtA6-uezDZ_9u0074J1vkFK88U1k',
    appId: '1:274382156691:android:9ae36abf6066f1cc096e66',
    messagingSenderId: '274382156691',
    projectId: 'bakecakeadmin',
    storageBucket: 'bakecakeadmin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4BytKyBT85ZTJSpHXbvwgZNoWIRpcm9M',
    appId: '1:274382156691:ios:b11776c4638cb561096e66',
    messagingSenderId: '274382156691',
    projectId: 'bakecakeadmin',
    storageBucket: 'bakecakeadmin.appspot.com',
    iosClientId: '274382156691-8o9m918e0ks1iadbp1ntlfltis86165i.apps.googleusercontent.com',
    iosBundleId: 'com.example.bakeNCakeUserSide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4BytKyBT85ZTJSpHXbvwgZNoWIRpcm9M',
    appId: '1:274382156691:ios:b66404a94fdfab71096e66',
    messagingSenderId: '274382156691',
    projectId: 'bakecakeadmin',
    storageBucket: 'bakecakeadmin.appspot.com',
    iosClientId: '274382156691-a6051dro7dsi62d1o3nun4np2eqmuc3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.bakeNCakeUserSide.RunnerTests',
  );
}
